### ISSUE TITLE
Prometheus not able to scrape Kubelet

### ISSUE THREAD

**Issue by andersflemmen** [openshift/cluster-monitoring-operator#102]
I have the cluster monitoring operator running in Minishift (minishift v1.24.0+8a904d0), but Prometheus fails to scrape the Kubelet with the following errors:

```
Get https://10.0.2.15:10250/metrics: x509: certificate is valid for 127.0.0.1, not 10.0.2.15
Get https://10.0.2.15:10250/metrics/cadvisor: x509: certificate is valid for 127.0.0.1, not 10.0.2.15
```

Is this a Minishift problem?

**Comment by praveenkumar** [comment]
> minishift, do you have any ideas?

@durandom I don't have any idea around this, is it something you can able to do with `oc cluster up` successfully, if yes then we can look from minishift side because under the hood it is same oc cluster up.

> BTW, the same happens if I do minishift console, I get redirected to 127.0.0.1

@durandom that is something already resolved in latest version of minishift because of a issue with `oc cluster up` the cluster redirection doesn't work so you need to put proper URI `https://<VM_IP>/console` so no redirection required.

**Comment by sjenning** [comment]
This was fixed.  Then just recently broken again by https://github.com/openshift/cluster-kube-controller-manager-operator/pull/132.  I don't think Prometheus is updating to trust the CA the KCM is signing with,

**Comment by s-urbaniak** [comment]
closing out as fixed.
