### ISSUE TITLE
Disable Alerting rules on prometheus-k8s instance

### ISSUE THREAD

**Issue by nabbdl** [openshift/cluster-monitoring-operator#124]
Is there any way to disable some rules on the "prometheus-k8s" instance. I already tried to modify the prmetheusrule  "prometheus-k8s-rules", which work for some seconds but it is overwrited with the former configuration probably by the prometheus operator.

**Comment by squat** [comment]
@nabbdl no, unfortunately you cannot disable rules that are part of the Cluster Monitoring Operator's default stack. The rules are compiled into the binary itself [0] and will get redeployed if they are manually edited. This feature is important so that we can automatically update and reconcile the entire monitoring stack when new versions are released and the Cluster Monitoring Operator is updated.

What rules do you want to disable? Would silencing alerting rules in Alertmanager be sufficient for your case?

[0] https://github.com/openshift/cluster-monitoring-operator/blob/master/pkg/manifests/bindata.go#L1143

**Comment by nabbdl** [comment]
In fact I would like to disable "KubeSchedulerDown"   and "KubeControllerManagerDown". I am running OpenShift Origin v3.9 (not the containerized version) and the monitored pods (kube-scheduler and kube-controller)
 doesn't exist on OpenShift (if I'm right). I would like also to disable Telemetric but there is already on open issue for this. 

Thank you for your help !
![print-screen](https://user-images.githubusercontent.com/32450290/46755245-e4423280-ccc4-11e8-898d-e375f8f9232c.PNG)

**Comment by s-urbaniak** [comment]
Closing out due to staleness.
