### ISSUE TITLE
Telemeter deployment references missing key `id` in secret

### ISSUE THREAD

**Issue by tobru** [openshift/cluster-monitoring-operator#139]
The deployment under `assets/telemeter-client/deployment.yaml` references the key `id` in the secret `assets/telemeter-client/secret.yaml` which does not exist, leading into a non-functional deployment.

**Comment by squat** [comment]
This is a known issue due to recent breaking behavior in the openshift serving cert controller. It is being fixed as we speak.

**Comment by tobru** [comment]
Thanks for answering!

**Comment by squat** [comment]
@pennpeng @tobru what version of openshift are you running?

**Comment by pennpeng** [comment]
@squat  openshift origin 3.11

**Comment by squat** [comment]
Ah ok, this is due to deploying the 4.0 tag of cluster monitoring operator on openshift 3.11. This will not work. Telemeter client is not supposed to be deployed on OpenShift 3.11. In fact, there are many other parts of the infrastructure that will not work correctly, e.g. service serving CA bundle is in a different format etc.
@pennpeng please make sure you use the 3.11 image tag of cluster-monitoring-operator

**Comment by s-urbaniak** [comment]
Closing out due to staleness.
