### ISSUE TITLE
Master disappearance is not detected

### ISSUE THREAD

**Issue by X-dark** [openshift/cluster-monitoring-operator#298]
When a master disappear completely, no alert is triggered.

It seems that Prometheus loose tracks of the metrics related to the deleted master ( `up{job="apiserver"}`, `up{job="etcd"}`, `up{job="kube-controllers"}`,... no longer list the deleted instance). All remaining instances are up and thus no alert is triggered.

**Comment by squat** [comment]
@X-dark
up is kind of a special time series. it is automatically generated by prometheus for targets that it is configured to scrape. when your node disappears, the containers comprising your service are re-discovered and the target is reconfigured with fewer instances. Because of this, the up time series for that target will no longer exist.

All other time series relating to that node should still exist in older time-ranges, e.g. if you query for:
```
machine_cpu_cores{node="<NODE-NAME>"}
```
and set the time range to a time when the node existed, do metrics appear?

**Comment by s-urbaniak** [comment]
Closing out due to staleness.
