### ISSUE TITLE
[RFE]: Allow alerting rule thresholds to be changed

### ISSUE THREAD

**Issue by aneagoe** [openshift/cluster-monitoring-operator#937]
Currently, there doesn't seem to be an officially supported way to adjust thresholds on alerting rules. Thresholds are tunables which should be adjusted to every environment and use-case. One-size-fits-all approach is far from ideal in this case.

**Comment by lilic** [comment]
@aneagoe Thanks for your feature request! Do you mind describing your ideal scenario, how adjusting would work for you best? And any specific cases you ran into problems? Did you have a problem with one specific alert or all of them, any version of openshift, etc. thanks!

**Comment by aneagoe** [comment]
@lilic thanks for the prompt response. The idea would be to be able to change or override the thresholds that come out of the box. I would be happy with any mechanism to be honest.For example, having a second, user-controlled, configmap or adding a new CRD for describing AlertingRule objects (although this seems a bit of an overkill maybe).
The particular issue we're observing is errors on node network interface. Due to our environment (Juniper QFX switch with jumbo frames) all our servers exhibit a low number of interface errors that are actually harmless (they happen on *all* servers connected to this switch, currently trying to determine root-cause). The current configuration trips if there are more than 10 errors for a particular interface in the last 2m. So it trips on all our nodes, we ignore it since we know it's a non-issue but like this (or by silencing) we wouldn't observe actual issues where the error-rate is actually high (ie in the hundreds).

**Comment by simonpasquier** [comment]
In the particular case of `NodeNetworkReceiveErrs` and `NodeNetworkTransmitErrs` alerts, maybe we should alert on the ratio of errors rather an absolute number?

```
rate(node_network_receive_errs_total[2m]) / rate(node_network_receive_packets_total[2m]) > 0.01
```

_I'm not saying that customizing alerts wouldn't be useful in general._

**Comment by sichvoge** [comment]
Hi @aneagoe. Thanks for coming back to us. Would you mind raising this with Red Hat support? They would usually go ahead and create a support case and attach this with an RFE in our pipeline. You can describe exactly what you have here so that they can add all these information to that RFE ticket.

After the RFE ticket is created, we will take this up as a team and see what we can do in this case. Small heads up, this will probably take a long time and nothing for this year anymore. The team is heads down to release a new feature that lets you and others use our Monitoring infrastructure to monitor your own stuff in a multi-tenant way. After that, we will use some time to harden our stack, improving performance and stability as well as overall resource consumption. Our interest is to keep a certain level of quality that we deliver and it is critical we also take time to lean back and work on these type of things from time to time.

**Comment by aneagoe** [comment]
@sichvoge I'm only using OKD4; we don't have RedHat support nor OCP. I doubt I can raise this with RedHat support without that. And I do understand that it can take time to have this implemented, as long as this is on the radar, I'm fine with that. I would also expect that more people would request this as environments are upgraded to OKD/OCP 4.x.

**Comment by edvinas31** [comment]
Same for me. I am also using OKD (however 3.11) version. And I was unable to find any way to edit prometheus rules file permanently. I know that it is possible to change Alertmanager file using ansible variable openshift_cluster_monitoring_operator_alertmanager_config (https://docs.openshift.com/container-platform/3.11/install_config/prometheus_cluster_monitoring.html). It would be great to be able customise alert rules and to change prometheus configuration using ansible variable. Personally I would like to add additional namespace to "KubePodCrashLooping" rule. Moreover, we do not have RedHat support. When I raise a ticket they told me that I do not have a subscription

**Comment by sichvoge** [comment]
Hi everyone, sorry for the late response. We will most likely not give permissions to change the rules we ship. Metric names can change (especially in K8s - see 1.14) so will rules and dashboards and any changes to our rule files (which a lot come from upstream projects) will make any upgrade more difficult and at worst, very disruptive.

Nevertheless, our current idea is to allow you to define your own rules in a platform-related namespace (which is currently not allowed) based upon on an existing rule. Basically, you could "clone" an existing rule and modify it so that it fits your use case. You can then also silence ours if you need to do so. That way, upgrades are still safe since we would only upgrade our out of the box and with 4.6, we have started to be much more clear when we change rules, metrics, and dashboards so that you have more visibility if you need to take actions as well.
